### ISSUE TITLE
`gi.repository.GLib.GError: gtk-builder-error-quark: /usr/lib/linuxmint/mintSources/mintsources.glade:308:1 Invalid object type 'XAppStackSidebar' (6)`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/mintsources#1]
https://github.com/linuxmint/mintsources/blob/master/usr/lib/linuxmint/mintSources/mintsources.glade#L307C34-L307C50

```bash
mintsources
```
```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1978, in <module>
    Application(os_codename).run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 857, in __init__
    self.builder.add_from_file(glade_file)
gi.repository.GLib.GError: gtk-builder-error-quark: /usr/lib/linuxmint/mintSources/mintsources.glade:308:1 Invalid object type 'XAppStackSidebar' (6)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintSources_mintSources.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1978, in <module>
    Application(os_codename).run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 857, in __init__
    self.builder.add_from_file(glade_file)
gi.repository.GLib.GError: gtk-builder-error-quark: /usr/lib/linuxmint/mintSources/mintsources.glade:308:1 Invalid object type 'XAppStackSidebar' (6)
```

On a relative laptop. While I do not have this issue on my Framework. Version 2.2.8 on both laptops. Let us investigate dependencies (see below).

Same behavior graphically, from root shell and from user shell and provide password.

`"XAppStackSidebar" "mintsources"` does not bring interesting results on DuckDuckGo and Google, except [this unclear one](https://forums.linuxmint.com/viewtopic.php?p=1844413). But the thread is locked and there does not seem to be user profiles, hence it does not seem possible to ask this person more details.

```bash
sudo apt install python3-apt python3-gi python3-gi-cairo python3-pycurl python3-requests mint-common gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-pango-1.0 gir1.2-vte-2.91 gir1.2-xapp-1.0 iso-flag-png inxi lsb-release
```
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iso-flag-png is already the newest version (1.0.2).
mint-common is already the newest version (2.3.0).
gir1.2-xapp-1.0 is already the newest version (2.6.1+victoria).
gir1.2-glib-2.0 is already the newest version (1.72.0-1).
gir1.2-vte-2.91 is already the newest version (0.68.0-1).
lsb-release is already the newest version (11.1.0ubuntu4).
python3-pycurl is already the newest version (7.44.1-4build1).
inxi is already the newest version (3.3.13-1-1).
gir1.2-gdkpixbuf-2.0 is already the newest version (2.42.8+dfsg-1ubuntu0.2).
gir1.2-gtk-3.0 is already the newest version (3.24.33-1ubuntu2).
gir1.2-pango-1.0 is already the newest version (1.50.6+ds-2ubuntu1).
python3-apt is already the newest version (2.4.0ubuntu2).
python3-gi is already the newest version (3.42.1-0ubuntu1).
python3-gi-cairo is already the newest version (3.42.1-0ubuntu1).
python3-requests is already the newest version (2.25.1+dfsg-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

Same output on both laptops.

https://github.com/linuxmint/mintsources/blob/9134dca6b2f1608a3ab4c2b3dc48de970bf73d37/usr/lib/linuxmint/mintSources/mintSources.py#L20-L23

https://github.com/linuxmint/mintsources/blob/9134dca6b2f1608a3ab4c2b3dc48de970bf73d37/usr/lib/linuxmint/mintSources/mintSources.py#L857

Have on both laptop `PyGObject` `import`ing `gi` 3.46.0.

Just searching the web for `"Invalid object type ‘XAppStackSidebar’"` seems appropriate.

**Comment by Benjamin-Loison** [comment]
Can in the meanwhile manually modify `/etc/apt/sources.list.d/official-{package,source}-repositories.list`.
